development:
  adapter: postgresql
  encoding: utf8
  database: keyboard_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: keyboard_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: keyboard_production
  pool: 5
  username: 
  password:
